export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const STUDENT_REGISTER_SUCCESS = "STUDENT_REGISTER_SUCCESS";
export const STUDENT_REGISTER_FAIL = "STUDENT_REGISTER_FAIL";

export const STUDENT_USER_LOADED = "STUDENT_USER_LOADED";
export const STUDENT_AUTH_ERROR = "STUDENT_AUTH_ERROR";

export const STUDENT_LOGIN_SUCCESS = "STUDENT_LOGIN_SUCCESS";
export const STUDENT_LOGIN_FAIL = "STUDENT_LOGIN_FAIL";

export const STUDENT_LOGOUT = "STUDENT_LOGOUT";

//Profile
export const STUDENT_GET_PROFILE = "STUDENT_GET_PROFILE";
export const STUDENT_GET_PROFILES = "STUDENT_GET_PROFILES";
export const STUDENT_UPDATE_PROFILE = "STUDENT_UPDATE_PROFILE";

export const STUDENT_CLEAR_PROFILE = "STUDENT_CLEAR_PROFILE";
export const STUDENT_PROFILE_ERROR = "STUDENT_PROFILE_ERROR";

export const STUDENT_ACCOUNT_DELETED = "STUDENT_ACCOUNT_DELETED";

export const STUDENT_GET_EVENTS = "STUDENT_GET_EVENTS";
export const STUDENT_UPDATE_EVENTS = "STUDENT_UPDATE_EVENTS";
export const STUDENT_CLEAR_EVENTS = "STUDENT_CLEAR_EVENTS";

export const STUDENT_SAVE_EVENTS = "STUDENT_SAVE_EVENTS";
export const STUDENT_GET_NEW_EVENTS = "STUDENT_GET_NEW_EVENTS";
export const STUDENT_UPDATE_NEW_EVENTS = "STUDENT_UPDATE_NEW_EVENTS";
export const STUDENT_CLEAR_NEW_EVENTS = "STUDENT_CLEAR_NEW_EVENTS";

export const STUDENT_EDIT_EVENTS = "STUDENT_EDIT_EVENTS";
